// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterUserInput struct {
	Email string `json:"email"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
